# Generated by Django 3.2.2 on 2021-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='performedprocedures',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='performedprocedures',
            old_name='procedure_id',
            new_name='procedure',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='medication_id',
            new_name='medication',
        ),
    ]
